### PR TITLE
Default mail storage same as in manual

### PR DESCRIPTION
**Pull request by Kami-no**
No need to remember that if you use the manual.

### CODE REVIEW

**Comment by Udera** [comment]
````Spool for tasks waiting to be processed, e.g., print queues and outgoing mail queue.````
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

I don't think you want to store your emails at this location.

**Comment by Kami-no** [comment]
Well, /usr also is not an option...
Secondary hierarchy for '''read-only user data'''; contains the majority of (multi-)user utilities and applications.[6]

/var/mail or /var/mbox

Most Linux distributives (including Debian and RHEL) prefer /var/www for web-servers' home directory. /var is the optimal location for such data.

**Comment by Udera** [comment]
/var/mail is already used in Debian as mailbox for system users.
We could use /var/vmail, /var/mbox, or /var/vexim ... in the end the manual only suggests a location

**Comment by rimas-kudelis** [comment]
Just FYI, I myself use /var/mail/vexim for this. Debian using /var/mail hasn't got in my way yet, but if we want to be cautious, /var/vmail sounds just fine to me.

**Comment by Kami-no** [comment]
As you wish...

**Comment by Kami-no** [comment]
BTW you've marked "duplicate" the wrong thread.

**Comment by rimas-kudelis** [comment]
Please squash the commits, if you don't mind.
Regarding marking the thread duplicate: it's just a flag anyway, but I thought the other issue describes this issue better. Once the PR is merged, both issues will be closed anyway (especially if you say `fixes #50` in your commit message :) ).

**Comment by rimas-kudelis** [comment]
Still two commits?

**Comment by rimas-kudelis** [comment]
Your changes have been merged. Thank you! :)

**Pull request closed without merging**
